@startuml
'https://plantuml.com/class-diagram

enum LessonFrequency
{
    Odd, Even, Persistent
}

class Lesson 
{
    + LessonFrequency Frequency
    + DateTime Begin
    + TimeSpan Span
}

class Schedule
{
    + List<Lesson> Lessons
    --
    + bool IntersectsWith(Schedule other)
}

class Student
{
    + Guid Id
    + string Name
    + Group Group
}

class StudyStream 
{
    + Guid Id
    + string Name
    + Schedule Schedule
    + int Capacity
    + List<Student> Students
    --
    + 
}

class StudySubject 
{
    + Guid Id
    + string Name
    + string ShortName
    + List<StudyStream> Streams
    --
    + StudySubject AddStream(int number, Schedule schedule)
}

'
'
'

Lesson *- LessonFrequency

Schedule ||--{ Lesson

StudyStream ||--{ Student
StudyStream ||--|| Schedule

StudySubject ||--{ StudyStream

@enduml